baseURL = "https://foulab.org"
languageCode = "en-us"
title = "Welcome to Foulab! - foulab.org"
theme = "foulab-2018"

enableGitInfo = true

disableKinds = ['taxonomy', 'term']

paginate = 7
paginatePath = "p"
